# Site settings
title: Blog for Creative Design and Prototyping Course
description: My documentation for course exercises and project are available on this blog.
keywords: Modern, Blogging, Fun, Design, Project, Exercises, FabLab, Study
author: Onur Özüduru
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

plugins:
  - jemoji
